- name: Run roles and SCAP audit
  hosts: all
  remote_user: ansible
  become: true
  roles:
    - role : ./roles/install-scap
    - role : ./roles/dnf-auto
    - role : ./roles/gpg_check
    - role : ./roles/pam-all
    - role : ./roles/authselect
    - role : ./roles/pwd_spec
    - role : ./roles/pwd_reuse
    - role : ./roles/hash_pwd_auth
    - role : ./roles/hash_sys_auth
    - role : ./roles/lockout
    - role : ./roles/scan-scap
